### PR TITLE
added advanced validation from XLIFF 2.1 Candidate OASIS Standard

### PR DESCRIPTION
**Pull request by DavidFatDavidF**
moved the custom sch to custom sch subfolder
added all xsd, sch, and NVDL from XLIFF 2.1 Candidate OASIS Standard into 2.1 subfolders
Note: 2.1 validation artifacts can be used to validate 2.0

### CODE REVIEW

**Comment by raducoravu** [comment]
Thanks for the contribution @DavidFatDavidF  
Some observations:
Looking at the "XLIFF 2.1" framework extension you created, it would seem that you still need to edit the content from the "Association rules" tab to make it match only XLiff 2.1 documents. Also in the "Schema", "Templates" and "Catalogs" tab you could point to the 2.1 equivalents. 
So some new 2.1 file templates would also be useful.  I do not know much about XLiff but if you make the changes I could try to work with it a little bit on my side.

**Comment by DavidFatDavidF** [comment]
Thanks for this @raducoravu 
I've been travelling but looking at it again now. In fact 2.1 is backwards compatible and 2.0 is forwards compatible so it was intended that the 2.1 extension catches all XLIFF 2.* files as it provides superior validation capabilities compared to just the xsds available for 2.0. This said, there are some finer points between the 2.0 and 2.1 modules, so I think both 2.0 and 2.1 framework files should be edited.. I will be back with edited 2.0 and 2.1 framework files, and you should be hopefully able to take it from there.. 
Maybe in the future it would be best to separate the XLIFF 1.2 framework from the XLIFF 2.* framework, as the structure is quite different (and 1.* is legacy and no longer developed) and it makes more sense to have one developing framework for all XLIFF 2.* But I am afraid this would need to be done on your end..

**Comment by raducoravu** [comment]
Thanks @DavidFatDavidF, I appreciate this, after you make your changes I will find some time to merge them in.

**Comment by raducoravu** [comment]
Thanks for the pull request, I did not merge it but I looked at your changes and I just updated the project with XLiff 2.1 support, I renamed the "xsd" folder to "schemas" in order to add all the XLiff 2.1 schemas there.

**Comment by raducoravu** [comment]
Probably the CSS used to edit the XLiff docs in the Author mode should be updated in order to take into account new XLiff 2.1 constructs but I know very little about the specs.

**Pull request closed without merging**
